/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* src = "alu.v:1.1-9.10" *)
module alu(a, b, sel, result);
  (* src = "alu.v:1.24-1.25" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "alu.v:1.38-1.39" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "alu.v:1.40-1.43" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "alu.v:1.60-1.66" *)
  output [1:0] result;
  reg [1:0] result;
  (* src = "alu.v:2.1-8.4" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  INVX1 _09_ (
    .A(a[0]),
    .Y(_02_)
  );
  INVX1 _10_ (
    .A(sel[0]),
    .Y(_03_)
  );
  INVX1 _11_ (
    .A(sel[1]),
    .Y(_04_)
  );
  XOR2X1 _12_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_[0])
  );
  NAND3X1 _13_ (
    .A(a[0]),
    .B(sel[0]),
    .C(_04_),
    .Y(_05_)
  );
  OAI21X1 _14_ (
    .A(_03_),
    .B(sel[1]),
    .C(_02_),
    .Y(_06_)
  );
  NAND3X1 _15_ (
    .A(b[0]),
    .B(_05_),
    .C(_06_),
    .Y(_07_)
  );
  XOR2X1 _16_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_08_)
  );
  XNOR2X1 _17_ (
    .A(_07_),
    .B(_08_),
    .Y(_00_[1])
  );
  BUFX2 _18_ (
    .A(sel[1]),
    .Y(_01_)
  );
  (* src = "alu.v:2.1-8.4" *)
  always @*
    if (!_01_) result[0] = _00_[0];
  (* src = "alu.v:2.1-8.4" *)
  always @*
    if (!_01_) result[1] = _00_[1];
endmodule

(* src = "counter.v:1.1-8.10" *)
module counter(clk, rst, count);
  (* src = "counter.v:1.22-1.25" *)
  input clk;
  wire clk;
  (* src = "counter.v:1.32-1.35" *)
  input rst;
  wire rst;
  (* src = "counter.v:1.53-1.58" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  INVX1 _11_ (
    .A(count[3]),
    .Y(_04_)
  );
  INVX1 _12_ (
    .A(rst),
    .Y(_05_)
  );
  AND2X1 _13_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_06_)
  );
  NAND3X1 _14_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .Y(_07_)
  );
  OAI21X1 _15_ (
    .A(count[2]),
    .B(_06_),
    .C(_05_),
    .Y(_08_)
  );
  AOI21X1 _16_ (
    .A(count[2]),
    .B(_06_),
    .C(_08_),
    .Y(_00_)
  );
  OAI21X1 _17_ (
    .A(count[1]),
    .B(count[0]),
    .C(_05_),
    .Y(_09_)
  );
  NOR2X1 _18_ (
    .A(_06_),
    .B(_09_),
    .Y(_01_)
  );
  NOR2X1 _19_ (
    .A(count[0]),
    .B(rst),
    .Y(_02_)
  );
  OAI21X1 _20_ (
    .A(_04_),
    .B(_07_),
    .C(_05_),
    .Y(_10_)
  );
  AOI21X1 _21_ (
    .A(_04_),
    .B(_07_),
    .C(_10_),
    .Y(_03_)
  );
  (* src = "counter.v:2.1-7.5" *)
  DFFPOSX1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[0])
  );
  (* src = "counter.v:2.1-7.5" *)
  DFFPOSX1 _23_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  (* src = "counter.v:2.1-7.5" *)
  DFFPOSX1 _24_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[2])
  );
  (* src = "counter.v:2.1-7.5" *)
  DFFPOSX1 _25_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule

(* src = "mux.v:1.1-3.10" *)
module mux(in1, in2, sel, y);
  (* src = "mux.v:1.23-1.26" *)
  input [1:0] in1;
  wire [1:0] in1;
  (* src = "mux.v:1.38-1.41" *)
  input [1:0] in2;
  wire [1:0] in2;
  (* src = "mux.v:1.48-1.51" *)
  input sel;
  wire sel;
  (* src = "mux.v:1.65-1.66" *)
  output [1:0] y;
  wire [1:0] y;
endmodule

(* top =  1  *)
(* src = "top.v:1.1-16.10" *)
module top(clk, rst, alu_sel, mux_sel, soc_out);
  (* src = "top.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "top.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "top.v:4.8-4.15" *)
  input alu_sel;
  wire alu_sel;
  (* src = "top.v:5.8-5.15" *)
  input mux_sel;
  wire mux_sel;
  (* src = "top.v:6.15-6.22" *)
  output [1:0] soc_out;
  wire [1:0] soc_out;
  (* src = "top.v:9.13-9.20" *)
  wire [1:0] alu_out;
  (* src = "top.v:8.13-8.18" *)
  wire [3:0] count;
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:12.6-13.18" *)
  alu u_alu (
    .a(count[3:2]),
    .b(count[1:0]),
    .result(alu_out),
    .sel({ 1'h0, alu_sel })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:11.10-11.56" *)
  counter u_counter (
    .clk(clk),
    .count(count),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:14.6-15.13" *)
  mux u_mux (
    .in1(count[3:2]),
    .in2(alu_out),
    .sel(mux_sel),
    .y(soc_out)
  );
endmodule
