/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "and_gate.v:1.1-3.10" *)
module and_gate(a, b, y);
  (* src = "and_gate.v:1.23-1.24" *)
  input a;
  wire a;
  (* src = "and_gate.v:1.32-1.33" *)
  input b;
  wire b;
  (* src = "and_gate.v:1.42-1.43" *)
  output y;
  wire y;
  AND2X1 _0_ (
    .A(a),
    .B(b),
    .Y(y)
  );
endmodule
